"""add_multi_user_isolation

Revision ID: 026566c69ec9
Revises: afc23e883149
Create Date: 2026-08-18 19:51:06.408856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026566c69ec9'
down_revision: Union[str, Sequence[str], None] = 'afc23e883149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('store_id', sa.Integer(), nullable=True))

    # Backfill existing data to the default store
    connection = op.get_bind()
    store_result = connection.execute(sa.text("SELECT id FROM stores LIMIT 1")).fetchone()
    if store_result:
        store_id = store_result[0]
    else:
        connection.execute(sa.text(
            "INSERT INTO stores (name, address, phone, email, created_at) "
            "VALUES ('Demo Store', '123, MG Road, Bengaluru, Karnataka', '+91 9876543210', 'store@storepilot.com', NOW())"
        ))
        store_result = connection.execute(sa.text("SELECT id FROM stores ORDER BY id DESC LIMIT 1")).fetchone()
        store_id = store_result[0]

    connection.execute(sa.text(f"UPDATE users SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE categories SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE products SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE suppliers SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE customers SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE sales SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE purchases SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE notifications SET store_id = {store_id} WHERE store_id IS NULL"))
    connection.execute(sa.text(f"UPDATE inventory_transactions SET store_id = {store_id} WHERE store_id IS NULL"))

    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint('uix_store_category_name', 'categories', ['store_id', 'name'])
    op.create_foreign_key(None, 'categories', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inventory_transactions', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_unique_constraint('uix_store_product_sku', 'products', ['store_id', 'sku'])
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchases', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=False)
    op.create_unique_constraint('uix_store_sale_invoice', 'sales', ['store_id', 'invoice_number'])
    op.create_foreign_key(None, 'sales', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'suppliers', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'store_id')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'store_id')
    op.drop_column('stores', 'business_type')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint('uix_store_sale_invoice', 'sales', type_='unique')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.drop_column('sales', 'store_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'store_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uix_store_product_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'store_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'store_id')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'store_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'store_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uix_store_category_name', 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'store_id')
    # ### end Alembic commands ###
